### ISSUE TITLE
caddy container kepps restarting if stalwart container is in the stack

### ISSUE THREAD

**Issue by hgterra** [szaimen/aio-caddy#25]
If you have stalwart mail in the stack, the first time you stop docker service (or reboot the box) the detection just goes fine. But when you do for the second time, caddy keeps restarting.
I've found a solution, changing the detection of stalwart in start.sh
I've changed line 53
if [ -n "$(dig A +short nextcloud-aio-stalwart)" ] && ! grep -q "mail.$NC_DOMAIN" /Caddyfile; then
by 
if [ -n "$(dig A +short nextcloud-aio-stalwart)" ] && ! grep -q "mail.{\$NC_DOMAIN}" /Caddyfile; then

**Comment by hgterra** [comment]
Sure. Pull request submitted.
Hope I did it OK, it's my first pull request

**Comment by szaimen** [comment]
Yes, thanks! Should be available when https://github.com/szaimen/aio-caddy/actions/runs/7888438685 is done :)
