### ISSUE TITLE
Allow to setup custom caddy rules

### ISSUE THREAD

**Issue by AiroPi** [szaimen/aio-caddy#28]
If we have something else running on our server besides AIO, it might be interesting to allow the aio-caddy container to import rules from users. Perhaps we could mount a volume pointing to the local `$PWD/caddy` directory where users can add some Caddy files, and then the `start.sh` script can import them into the Caddyfile.

I'm new to Caddy, but I think this is something that's possible. 

I just want your opinion before making any PR. This could allow users to easily set up Caddy with automatic reverse proxies for other community containers without needing to set up a reverse proxy for Nextcloud AIO just to add other rules.

**Comment by AiroPi** [comment]
This would also require `--add-host host.docker.internal:host-gateway` for the caddy container in order to access the localhost on linux systems.

**Comment by jaker-dotcom** [comment]
I am interested in hosting other services.  Just so I get this right: 
1. Nextcloud AIO can be run from the first startup with caddy community container and all nextcloud services are then managed via caddy. Following https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md would be pointless.
2. Additional services that are not part of AIO can also be configured via a caddyfile that must be placed via shell in the container created at /data/caddy-imports/any_name.

Thanks for maintaining!
